#!/usr/bin/python

import sys
from BeautifulSoup import BeautifulSoup


def unescape_xhtml(s):
	htmlInput = '<html>' + s
	# Livejournal stream has &apos; so we must use XHTML_ENTITIES
	unescaped = BeautifulSoup(
		htmlInput, convertEntities=BeautifulSoup.XHTML_ENTITIES
	).contents[0].string
	if not unescaped:
		unescaped = u""
	# Convert BeautifulSoup thing into a real str object
	return unescaped.encode("utf-8")


def decode_entities(s):
	assert not '<' in s, s
	assert not '>' in s, s
	if '&' in s:
		s = unescape_xhtml(s)
	return s


def main():
	for s in sys.stdin:
		print decode_entities(s.rstrip())


if __name__ == '__main__':
	main()
