#!/usr/bin/python

import sys

start_s, end_s = sys.argv[1], sys.argv[2]

for line in sys.stdin:
	line = line.rstrip()
	if not start_s in line or not end_s in line:
		continue
	print line[line.find(start_s) + len(start_s):line.rfind(end_s)]
