#!/usr/bin/python

import sys

prefixes = sys.argv[1].split(',')
suffixes = sys.argv[2].split(',')

for line in sys.stdin:
        for p in prefixes:
                for s in suffixes:
                        print p + line.rstrip() + s
